spring.application.name=sandbox

# Configuracion de MySQL - Aiven
# Agregamos sslMode=REQUIRED y trustServerCertificate=true para evitar bloqueos de certificados
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de JPA e Hibernate (CRÍTICO: Define el dialecto explícito para solucionar el error de tests)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true